/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkspacesRouteImport } from './routes/_app/workspaces'
import { Route as AppTriggersRouteImport } from './routes/_app/triggers'
import { Route as AppJobsRouteImport } from './routes/_app/jobs'
import { Route as AppFleetRouteImport } from './routes/_app/fleet'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppConversationsRouteImport } from './routes/_app/conversations'
import { Route as AppWorkflowsIndexRouteImport } from './routes/_app/workflows.index'
import { Route as AppRunsIndexRouteImport } from './routes/_app/runs.index'
import { Route as AppWorkflowsIdRouteImport } from './routes/_app/workflows.$id'
import { Route as AppRunsIdRouteImport } from './routes/_app/runs.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspacesRoute = AppWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AppRoute,
} as any)
const AppTriggersRoute = AppTriggersRouteImport.update({
  id: '/triggers',
  path: '/triggers',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppFleetRoute = AppFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConversationsRoute = AppConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowsIndexRoute = AppWorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => AppRoute,
} as any)
const AppRunsIndexRoute = AppRunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowsIdRoute = AppWorkflowsIdRouteImport.update({
  id: '/workflows/$id',
  path: '/workflows/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppRunsIdRoute = AppRunsIdRouteImport.update({
  id: '/runs/$id',
  path: '/runs/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conversations': typeof AppConversationsRoute
  '/dashboard': typeof AppDashboardRoute
  '/fleet': typeof AppFleetRoute
  '/jobs': typeof AppJobsRoute
  '/triggers': typeof AppTriggersRoute
  '/workspaces': typeof AppWorkspacesRoute
  '/runs/$id': typeof AppRunsIdRoute
  '/workflows/$id': typeof AppWorkflowsIdRoute
  '/runs/': typeof AppRunsIndexRoute
  '/workflows/': typeof AppWorkflowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conversations': typeof AppConversationsRoute
  '/dashboard': typeof AppDashboardRoute
  '/fleet': typeof AppFleetRoute
  '/jobs': typeof AppJobsRoute
  '/triggers': typeof AppTriggersRoute
  '/workspaces': typeof AppWorkspacesRoute
  '/runs/$id': typeof AppRunsIdRoute
  '/workflows/$id': typeof AppWorkflowsIdRoute
  '/runs': typeof AppRunsIndexRoute
  '/workflows': typeof AppWorkflowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/conversations': typeof AppConversationsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/fleet': typeof AppFleetRoute
  '/_app/jobs': typeof AppJobsRoute
  '/_app/triggers': typeof AppTriggersRoute
  '/_app/workspaces': typeof AppWorkspacesRoute
  '/_app/runs/$id': typeof AppRunsIdRoute
  '/_app/workflows/$id': typeof AppWorkflowsIdRoute
  '/_app/runs/': typeof AppRunsIndexRoute
  '/_app/workflows/': typeof AppWorkflowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conversations'
    | '/dashboard'
    | '/fleet'
    | '/jobs'
    | '/triggers'
    | '/workspaces'
    | '/runs/$id'
    | '/workflows/$id'
    | '/runs/'
    | '/workflows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conversations'
    | '/dashboard'
    | '/fleet'
    | '/jobs'
    | '/triggers'
    | '/workspaces'
    | '/runs/$id'
    | '/workflows/$id'
    | '/runs'
    | '/workflows'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/conversations'
    | '/_app/dashboard'
    | '/_app/fleet'
    | '/_app/jobs'
    | '/_app/triggers'
    | '/_app/workspaces'
    | '/_app/runs/$id'
    | '/_app/workflows/$id'
    | '/_app/runs/'
    | '/_app/workflows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workspaces': {
      id: '/_app/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AppWorkspacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/triggers': {
      id: '/_app/triggers'
      path: '/triggers'
      fullPath: '/triggers'
      preLoaderRoute: typeof AppTriggersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fleet': {
      id: '/_app/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof AppFleetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conversations': {
      id: '/_app/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AppConversationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workflows/': {
      id: '/_app/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof AppWorkflowsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/runs/': {
      id: '/_app/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof AppRunsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workflows/$id': {
      id: '/_app/workflows/$id'
      path: '/workflows/$id'
      fullPath: '/workflows/$id'
      preLoaderRoute: typeof AppWorkflowsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/runs/$id': {
      id: '/_app/runs/$id'
      path: '/runs/$id'
      fullPath: '/runs/$id'
      preLoaderRoute: typeof AppRunsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppConversationsRoute: typeof AppConversationsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFleetRoute: typeof AppFleetRoute
  AppJobsRoute: typeof AppJobsRoute
  AppTriggersRoute: typeof AppTriggersRoute
  AppWorkspacesRoute: typeof AppWorkspacesRoute
  AppRunsIdRoute: typeof AppRunsIdRoute
  AppWorkflowsIdRoute: typeof AppWorkflowsIdRoute
  AppRunsIndexRoute: typeof AppRunsIndexRoute
  AppWorkflowsIndexRoute: typeof AppWorkflowsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConversationsRoute: AppConversationsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFleetRoute: AppFleetRoute,
  AppJobsRoute: AppJobsRoute,
  AppTriggersRoute: AppTriggersRoute,
  AppWorkspacesRoute: AppWorkspacesRoute,
  AppRunsIdRoute: AppRunsIdRoute,
  AppWorkflowsIdRoute: AppWorkflowsIdRoute,
  AppRunsIndexRoute: AppRunsIndexRoute,
  AppWorkflowsIndexRoute: AppWorkflowsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
